### PR TITLE
Test pull request to BHplus and small fixes to begin with

### PR DESCRIPTION
**Pull request by wajidalikhan**

### CODE REVIEW

**Comment by menglu21** [comment]
Hi Wajid, thanks for the review of the code. 
1. changes in crab_help.py: since the python file under auto_crab_example is 'BH_postproc.py', we may use 'BH_postproc.py' here
2. I think we still need the 'Jet_pt_nom' since this branch will contain the jes and jer, and the branch is added before the BH module. 
3. As for the change in run.py, did you run it successfully after using 'BHplus', because the 'analysis' is the relative path to the module.

**Comment by wajidalikhan** [comment]
Hi Meng, thanks a lot for your time. 
1. Okay, I will remove the other crab stuff from BHplus and will focus on "BH_postproc.py"
2. There are other branches as well like MET_T1_pt which are to be added. Could you please point me to the module which is adding these brances Jet_pt_nom and Jet_mass_nom? 
Apparently, it appears that this module is doing the job, right
/afs/cern.ch/work/w/wajid/ttx/CMSSW_10_6_27/src/PhysicsTools/NanoAODTools/python/postprocessing/modules/jme/jetmetUncertainties.py

Which module is writing the MET_T1_pt branch? 

3. Yes, all the paths were adjusted in run.py to "PhysicsTools.NanoAODTools.postprocessing.BHplus.modules"

**Comment by wajidalikhan** [comment]
BTW "run.py" and "BH_postproc.py" are not very consistent with each other and not I am sure how they are being used for local testing and and to submit it over the crab.

**Comment by menglu21** [comment]
> Hi Meng, thanks a lot for your time.
> 
>     1. Okay, I will remove the other crab stuff from BHplus and will focus on "BH_postproc.py"
> 
>     2. There are other branches as well like MET_T1_pt which are to be added. Could you please point me to the module which is adding these brances Jet_pt_nom and Jet_mass_nom?
>        Apparently, it appears that this module is doing the job, right
>        /afs/cern.ch/work/w/wajid/ttx/CMSSW_10_6_27/src/PhysicsTools/NanoAODTools/python/postprocessing/modules/jme/jetmetUncertainties.py
> 
> 
> Which module is writing the MET_T1_pt branch?
> 
>     1. Yes, all the paths were adjusted in run.py to "PhysicsTools.NanoAODTools.postprocessing.BHplus.modules"

Hi Wajid,

2. The MET branch is introduced in this module, jetmetHelperRun2.py
3. the path should be not correct, i'm superized that it could run successfully after the changing. (but the crab job should be not affected by this change and the run.py is not used during job submission)

**Comment by menglu21** [comment]
> BTW "run.py" and "BH_postproc.py" are not very consistent with each other and not I am sure how they are being used for local testing and and to submit it over the crab.

just complement last comment, we use crab/crab_script.py for the crab jobs, the 'run.py' is just the 'crab_script.py', but with small changes to make it capable for the local input.

**Pull request merged**
